version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./config/nginx-custom-config.conf:/etc/nginx/conf.d/custom-config.conf:ro
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.docker
  mailhog:
     image: mailhog/mailhog
     restart: always
     expose:
      - "1025"
     networks:
      - default
      - mail
     ports:
       - "1025:1025"
       - "8025:8025"
networks:
  default:
    external:
      name: nginx-proxy
  mail:
    external:
      name: mail