version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.localhost
  mailhog:
     image: mailhog/mailhog
     restart: always
     expose:
      - "1025"
     networks:
      - default
      - mail
     ports:
       - "1025:1025"
       - "8025:8025"
networks:
  default:
    external:
      name: nginx-proxy
  mail:
    external:
      name: mail